name:                cq
version:             0.1.0.0
github:              "rootbeersoup/cq"
license:             BSD3
author:              "Darryl Abbate"
maintainer:          "rootbeersoup@gmail.com"
copyright:           "2019 Darryl Abbate"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rootbeersoup/cq#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- lens
- lens-aeson
- text
- wreq

library:
  source-dirs: src

executables:
  cq:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cq

tests:
  cq-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cq
